---
  - name: Configuration for dns01
    hosts: dns01
    become: true

    tasks:
      - name: Install latest version DNS packages
        ansible.builtin.package:
          name: 
            - bind9 
            - bind9utils
            - dnsutils
            - bind9-doc
          state: latest 
      
      - name: Enable and start bind9
        ansible.builtin.service:
          name: bind9
          enabled: true 
          state: started