---
  - name: Configure ESW2's interfaces and OSPF
    hosts: ESW2
    gather_facts: false
    become: true

    tasks:
      - name: Configure OSPF 
        cisco.ios.ios_ospfv2:
          config:
            processes:
              - areas:
                - area_id: '0'
                network:
                - address:  172.16.31.224
                  wildcard_bits: 0.0.0.31
                  area: '0'
                process_id: 1
              - areas:
                - area_id: '1'
                network:
                - address: 172.16.31.0
                  wildcard_bits: 0.0.0.127
                  area: '1'
                process_id: 1
          state: merged

      - name: Configure switch interfaces 
        cisco.ios.ios_l2_interfaces:
          config:
            - name: FastEthernet1/4
              mode: access 
              access:
                vlan: 240
            - name: FastEthernet1/5
              mode: access 
              access:
                vlan: 240
            - name: FastEthernet1/6
              mode: access 
              access:
                vlan: 240
          state: merged

      - name: Enable ESW2's interfaces
        cisco.ios.ios_interfaces:
          config:
            - name: FastEthernet1/4
              description: Access port for VLAN 240 (Servers) - dns01
              enabled: true
            - name: FastEthernet1/5
              description: Access port for VLAN 240 (Servers) - dhcp01
              enabled: true
            - name: FastEthernet1/6
              description: Access port for VLAN 240 (Servers) - dhcp01
              enabled: true

      - name: Show VLAN and OSPF configuration
        ios_command:
          commands:
            - show vlan-switch brief | exclude act/unsup
            - show ip interface brief | exclude down
            - show run | sec router ospf 1
        register: output

      - name: print output 
        debug:
          var: output.stdout_lines
