---
  - name: Configuration for dhcp01
    hosts: dhcp01
    become: true

    tasks:
      - name: Install latest version of isc-dhcp-server 
        ansible.builtin.package:
          name: isc-dhcp-server 
          state: latest 
      
      - name: Enable and start isc-dhcp-server 
        ansible.builtin.service:
          name: isc-dhcp-server 
          enabled: true 
          state: started
      
      
